name: Domky
version: 1.0
main: domky.MainDomky
api-version: 1.18

commands:
  +zarovnejTeren:
  +zarovnejTerenNahoru:
  +zakladovaDeska:
  +deskaZadani:
  +zedSeverJih:
  +zedVychodZapad:
  +domek:
  +radoveDomky:
  +panelak:
  +panelakOkna:
  +panelakOknaSchody:

