name: Domky
version: 1.0
main: domky.MainDomky
api-version: 1.18

commands:
  +zarovnejTeren:
  +zarovnejTerenNahoru:
  +vymazKolemHrace:
  +zakladovaDeska:
  +deskaZadani:
  +zedSeverJih:
  +zedVychodZapad:
  +domek:
  +panelak:
  +domekVetsiOkna:
  +schodySever:
  +schodyJih:
  +schodyVychod:
  +schodyZapad:
